### PR TITLE
enable add travis ci builds

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by xreef** [comment]
Thanks for your support.

**Comment by thijstriemstra** [comment]
@xreef can you also enable travis for this repository?

**Comment by xreef** [comment]
Ops, sorry thijstriemstra, I lost the last message.
What can I do to enable travis?
Bye Renzo

**Comment by thijstriemstra** [comment]
@xreef follow steps at https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github This PR added .travis.yml file already.

**Comment by thijstriemstra** [comment]
@xreef see my previous comment, can you enable travis for this repo? it should be as simple as authenticating using github, see link.

**Pull request merged**
